### ISSUE TITLE
Bug: Deleting field which is used in subsequent stage does not work

### ISSUE THREAD

**Issue by whscullin** [malloydata/malloy-composer#209]
Add a field, add a second stage, add the field to the second stage, attempt to remove the field

Stack: 
composer_page.js:3496 Error: Could not find carrier_count
    at GJt.getField (composer_page.js:3487:17831)
    at GJt.codeInfoForField (composer_page.js:3496:569)
    at GJt.getMalloyStringForStage (composer_page.js:3496:2876)
    at GJt.getMalloyString (composer_page.js:3496:4020)
    at GJt.getQueryStringForNotebook (composer_page.js:3496:192)
    at HJt.getQueryStringForNotebook (composer_page.js:3487:18743)

Previously, errors like this would cause the field in the second stage to turn into an error node

It seems like if there is only one field in the first stage, then the whole page goes white; otherwise the query still shows up, but some actions, like clicking on a field, don't work

**Comment by whscullin** [comment]
Any modifications that result in invalid models now return an error.
